#define     About                                      "关于"
#define     About_MiniGUI                              "关于 MiniGUI..."
#define     File                                       "文件"
#define     New                                        "新建"
#define     Open                                       "打开..."
#define     Save                                       "保存"
#define     Save_As                                    "另存为..."
#define     Close                                      "关闭"
#define     Exit                                       "退出"
#define     Dialogs                                    "对话框"
#define     Dialog1                                    "对话框1..."
#define     Dialog2                                    "对话框2..."
#define     Dialog3                                    "对话框3..."
#define     Dialog4                                    "对画框4..."
#define     Property_Sheet                             "表格..."
#define     Controls                                   "控件"
#define     Static_control                             "Static 控件"
#define     Button_control                             "Button 控件" 
#define     MenuButton_control                         "MenuButton 控件"
#define     Edit_control                               "Edit 控件"
#define     ListBox_control                            "ListBox 控件"
#define     ProgressBar_control                        "ProgressBar 控件"
#define     ComboBox_control                           "ComboBox 控件"
#define     NewToolBar_control                         "NewToolBar 控件"
#define     TrackBar_control                           "TrackBar 控件"
#define     ListView_control                           "ListView 控件"
#define     TreeView_control                           "TreeView 控件"
#define     MonthCalendar_control                      "MonthCalendar 控件"
#define     SpinBox_control                            "SpinBox 控件"
#define     CoolBar_control                            "CoolBar 控件"
#define     Control_Subclass                           "子控件"
#define     Time_Editor                                "时间编辑器"
#define     Are_you_sure_to_quit                       "确定要退出?"
#define     DlgTest                                    "对话框测试"
#define     The_dialog_and_control_demo                "对话框和控件"
#define     Push_Button                                "Push Button"
#define     Multiple_Lines_Push_Button                 "多行 Push Button"
#define     Normal_check_box                           "Normal check box"
#define     Normal_radio_button                        "Normal radio button"
#define     Auto_3_state_check_box                     "Auto 3-state check box"
#define     Auto_check_box_on_left                     "Auto check box on left"
#define     Push_like_check_box                        "Push-like check box"
#define     Auto_Radio_Button1                         "Auto Radio Button 1"
#define     Auto_Radio_Button2                         "Auto Radio Button 2"
#define     Auto_Radio_Button3                         "Auto Radio Button 3"
#define     Push_like_Radio1                           "Push-like Radio 1"
#define     Push_like_Radio2                           "Push-like Radio 2"
#define     Push_like_Radio3                           "Push-like Radio 3"
#define     Button_controls                            "Button 控件"
#define     This_is_a_simple_static_control            "这是 static控件"
#define     This_is_a_left_aligned_static_control      "左对齐 static 控件 (auto-wrap)."
#define     This_is_a_right_aligned_static_control     "右对齐 static 控件 (auto-wrap)."
#define     This_is_a_center_aligned_static_control    "居中 static 控件 (auto-wrap)."
#define     An_icon_static_control                     "icon static 控件 "
#define     A_bitmap_static_control                    "bitmap static 控件"
#define     A_bitmap_static_control_center             "bitmap static 控件(center)"
#define     A_black_box                                "black box:"
#define     A_gray_box                                 "gray box:"
#define     A_white_box                                "white box:"
#define     A_black_frame                              "black frame:"
#define     A_gray_frame                               "gray frame:"
#define     A_white_frame                              "white frame:"
#define     A_Group_Box                                "Group Box"
#define     Tabs_are_expanded                          "SS_LEFTNOWORDWRAP: \tTabs are expanded,\
                                                             but words are not wrapped. "
#define     Static_controls                            "Static 控件"
#define     Files_in_the_current_directory             "当前路径下的文件"
#define     Files_and_directories_in_the_current_directory_sorted       "当前路径下的文件 (sorted)"
#define     Files_and_directories_in_the_current_directory              "当前路径下的文件 (sorted, bitmap)"
#define     MenuButton_controls                                         "MenuButton 控件"
#define     simple_edit_box_with_fixed_font                             "edit box 等宽字体"
#define     this_is_a_simple_edit_box                                   "这是 simple edit box. 用等宽字体显示文字"
#define     single_line_edit_box_using_variable_width_font              "单行变宽字体 edit"
#define     this_is_a_single_line_edit_box                              "这是单行 edit box. 用变宽字体显示文字"
#define     multiple_line_edit_box_using_variable_width_font            "多行 edit box 变宽字体"
#define     multiple_line_edit_box_auto_wrap                            "多行 edit box (auto-wrap):"
#define     password_edit_box                                           "密码edit box:"
#define     typed_chars_to_upper_case                                   "大写字母:"
#define     typed_chars_to_lower_case                                   "小写字母:"
#define     read_only_edit_box                                          "只读edit box:"
#define     you_can_not_edit_the_text_in_this_edit_box                  "这个 edit 是不可以编辑的"
#define     limited_edit_box                                            "输入限制 edit box:"
#define     you_can_only_input_characters_in_box                        "在这个输如框你可以输入100个字母"
#define     right_aligned_text                                          "右对齐文字"
#define     center_aligned_text                                         "居中文字"
#define     edit_controls                                               "Edit 控件"

#define     a_normal_listbox_sorted                                     "listbox (sorted)"
#define     files_in_the_current_direcotory                             "所有文件"
#define     a_listbox_with_LBS_USEICON_style                            "listbox (LBS_USEICON)"
#define     a_listbox_with_LBS_MULTIPLESEL_style                        "listbox (LBS_MULTIPLESEL)"
#define     are_you_sure_to_delete_this_item                            "确信要删除?"
#define     Listbox                                                     "Listbox"
#define     add_me_to_the_box_bellow                                    "添加"
#define     Add                                                         "添加"
#define     Delete                                                      "删除"
#define     Find                                                        "查找"
#define     one_initially_checked_item                                  "默认选中"
#define     one_initially_not_checked_item                              "默认没有选中"
#define     one_initially_part_checked_item                             "默认 part-checked "
#define     ListBox_controls                                            "ListBox 控件"

#define     ProgressBar_controls                                        "ProgressBar 控件"

#define     ComboBox_controls                                           "ComboBox 控件"
#define     selected_                                                   "选中"
#define     Up                                                          "上"
#define     Prev                                                        "前"
#define     Next                                                        "后"
#define     Menu                                                        "菜单"
#define     NewToolBar_controls                                         "NewToolBar 控件"
#define     Delete_the_selected_item                                    "删除"
#define     Clear_all_item                                              "删除所有"
#define     select_item                                                 "全选"
#define     show_item                                                   "显示"
#define     del_column                                                  "删除 column"
#define     set_column_head                                             "设置 column 头"
#define     sorting_the_items                                           "排序"
#define     find_item                                                   "查找"
#define     open                                                        "打开"
#define     copy                                                        "拷贝"
#define     delete_                                                     "删除"
#define     rename                                                      "重命名"
#define     properties                                                  "性能"
#define     are_you_really_want_to_delete_this_file                     "确定要删除?"
#define     warning                                                     "警告"
#define     Are_you_really_want_to_open_this_file                       "想要打开这个文件吗?"
#define     Question                                                    "问题"
#define     File_name                                                   "文件名"
#define     File_size                                                   "文件大小"
#define     Category                                                    "类别"
#define     Last_modified_time                                          "最后修改日期"
#define     ListView_control                                            "ListView 控件"
#define     directory                                                   "字典"
#define     regular_file                                                "普通文件"

#define     Add_a_child_to_current_node                                 "添加一个节点"
#define     Find_a_node_in_treeview                                     "查找一个节点"
#define     Add                                                         "添加"
#define     Del                                                         "删除"
#define     Find                                                        "查找"
#define     TreeView_controls                                           "TreeView 控件"

#define     monthcalendar                                               "monthcalendar"
#define     get_current_day                                             "日"
#define     get_current_month                                           "月"
#define     get_current_year                                            "年"
#define     set_current_day                                             "设置日"
#define     set_current_month                                           "设置月"
#define     set_current_year                                            "设置年"
#define     set_current_date_as_today                                   "设置日期"
#define     get_first_day_of_week                                       "这星期第一天"
#define     get_current_date                                            "当前日期"
#define     get_today                                                   "今天"
#define     get_minreqrectsize                                          " minreqrectsize"
#define     set_current_date                                            "设置日期"
#define     set_color                                                   "设置颜色"
#define     get_color                                                   "提取颜色"
#define     MonthCalendar_control                                       "MonthCalendar 控件"

#define     About_SpinBox_control                                       "关于 SpinBox 控件 "
#define     About_SpinBox_message   "We use the SpinBox control in this Help Message Box.\n\n"  \
                                    "You can click the up arrow of the control to scroll up "    \
                                    "the message, and click the down arrow of the control to scroll down. "  \
                                    "You can also scroll the message by typing ArrowDown and ArrowUp keys.\n\n" \
                                    "In your application, you can call 'myWinHelpMessage' function " \
                                    "to build a Help Message box like this.\n\n" \
                                    "The Help Message Box is useful for some PDA-like applications.\n\n" \
                                    "The SpinBox control allways have the fixed width and height. " \
                                    "You can read the source of 'ext/control/spinbox.c' to know how to " \
                                    "build such a control.\n\n" \
                                    "If you want to know how to use this control, please read the " \
                                    "source of 'mywindows/helpwin.c' in the MiniGUI source tree." 

#define     Digit_only_box          "数字 box:"
#define     Alpha_only_box          "字母 box:"
#define     Normal_edit_box         "普通 edit box:"
#define     Subclass_of_Control     "子控件"

#define     property_caption        "属性页示例"                                    
#define     sure                    "确定"
#define     initializing            "VAM-CNC"
#define     doing                   "正在进行初始化..."
#define     please_select_mode      "请选择工作模式"
#define     mode                    "工作模式"
#define     mode_mdi                "MDI 方式"
#define     mode_bg                 "后置处理"
#define     mode_moving             "运动控制"
#define     mode_param              "参数设置"
#define     mode_helper             "辅助设备"
#define     combox                  "combobox"
#define     prompt                  "MDI 方式，手工编程。"

#define     machine_setting         "机床参数设置"
#define     fixpla_top_radius       "1.静止平台上正三角形外接圆半径"
#define     fixpla_bot_radius       "2.静止平台下正三角形外接圆半径"
#define     fixpla_height           "3.静止平台上下正三角形高差"
#define     fixpla_angle            "4.静止平台上下正三角形度差"
#define     movepla_top_radius      "5.动平台上正三角形外接圆半径"
#define     movepla_bot_radius      "6.动平台下正三角形外接圆半径"
#define     movepla_height          "7.动平台上下正三角形高差"
#define     movepla_angle           "8.动平台上下正三角形度差"
#define     platform_init_diff      "9.动静平台在初始位置时的度差"
#define     min_leg                 "A.机床最小腿长"
#define     max_leg                 "B.机床最大腿长"
#define     fixpla_distance         "C.上下静止平台之间的距离"
#define     cancel                  "取消"

#define     password_setting        "系统管理员口令设置" 
#define     enter_new_pwd           "请输入新的口令"
#define     pwd_valid               "密码有效"

#define     apply                   "应用"
#define     time_caption            "时间编辑器"
#define     time_editor             "这是时间编辑器。\n\n" \
                                                     "有输入焦点的之后，可以通过按键 <Down-Arrow>， "  \
                    "<Up-Arrow>， <PgDn> 和 <PgUp> "  \
                                                    " 来修改时间\n\n" \
                                                    "也可以通过点击旋钮控件来修改时间.\n\n"
#define      messageboxcap        "警告！"
#define      messageboxinfo        "请在第一个编辑框内输入信息。"