#define     About                                      "About"
#define     About_MiniGUI                              "About MiniGUI..."
#define     File                                       "File"
#define     New                                        "New"
#define     Open                                       "Open..."
#define     Save                                       "Save"
#define     Save_As                                    "Save As..."
#define     Close                                      "Close"
#define     Exit                                       "Exit"
#define     Dialogs                                    "Dialogs"
#define     Dialog1                                    "Dialog1..."
#define     Dialog2                                    "Dialog2..."
#define     Dialog3                                    "Dialog3..."
#define     Dialog4                                    "Dialog4..."
#define     Property_Sheet                             "Property Sheet..."
#define     Controls                                   "Controls"
#define     Static_control                             "Static control"
#define     Button_control                             "Button control" 
#define     MenuButton_control                         "MenuButton control"
#define     Edit_control                               "Edit control"
#define     ListBox_control                            "ListBox control"
#define     ProgressBar_control                        "ProgressBar control"
#define     ComboBox_control                           "ComboBox control"
#define     NewToolBar_control                         "NewToolBar control"
#define     TrackBar_control                           "TrackBar control"
#define     ListView_control                           "ListView control"
#define     TreeView_control                           "TreeView control"
#define     MonthCalendar_control                      "MonthCalendar control"
#define     SpinBox_control                            "SpinBox control"
#define     CoolBar_control                            "CoolBar control"
#define     Control_Subclass                           "Control Subclass"
#define     Time_Editor                                "Time Editor"
#define     Are_you_sure_to_quit                       "Are you sure to quit?"
#define     DlgTest                                    "DlgTest"
#define     The_dialog_and_control_demo                "The dialog and control demo"
#define     Push_Button                                "Push Button"
#define     Multiple_Lines_Push_Button                 "Multiple Lines Push Button"
#define     Normal_check_box                           "Normal check box"
#define     Normal_radio_button                        "Normal radio button"
#define     Auto_3_state_check_box                     "Auto 3-state check box"
#define     Auto_check_box_on_left                     "Auto check box on left"
#define     Push_like_check_box                        "Push-like check box"
#define     Auto_Radio_Button1                         "Auto Radio Button 1"
#define     Auto_Radio_Button2                         "Auto Radio Button 2"
#define     Auto_Radio_Button3                         "Auto Radio Button 3"
#define     Push_like_Radio1                           "Push-like Radio 1"
#define     Push_like_Radio2                           "Push-like Radio 2"
#define     Push_like_Radio3                           "Push-like Radio 3"
#define     Button_controls                            "Button controls"
#define     This_is_a_simple_static_control            "This is a simple static control."
#define     This_is_a_left_aligned_static_control      "This is a left-aligned static control (auto-wrap)."
#define     This_is_a_right_aligned_static_control     "This is a right-aligned static control (auto-wrap)."
#define     This_is_a_center_aligned_static_control    "This is a center-aligned static control (auto-wrap)."
#define     An_icon_static_control                     "An icon static control: "
#define     A_bitmap_static_control                    "A bitmap static control: "
#define     A_bitmap_static_control_center             "A bitmap static control (center): "
#define     A_black_box                                "A black box:"
#define     A_gray_box                                 "A gray box:"
#define     A_white_box                                "A white box: "
#define     A_black_frame                              "A black frame:"
#define     A_gray_frame                               "A gray frame:"
#define     A_white_frame                              "A white frame:"
#define     A_Group_Box                                "A Group Box"
#define     Tabs_are_expanded                          "SS_LEFTNOWORDWRAP: \tTabs are expanded,\
                                                             but words are not wrapped. "
#define     Static_controls                            "Static controls"
#define     Files_in_the_current_directory             "Files in the current directory"
#define     Files_and_directories_in_the_current_directory_sorted       "Files and directories in the current directory (sorted)"
#define     Files_and_directories_in_the_current_directory              "Files and directories in the current directory (sorted, bitmap)"
#define     MenuButton_controls                                         "MenuButton controls"
#define     simple_edit_box_with_fixed_font                             "Simple edit box with fixed font:"
#define     this_is_a_simple_edit_box                                   "This is a simple edit box. It uses fixed system font to display text"
#define     single_line_edit_box_using_variable_width_font              "Single-line edit box using variable-width font:"
#define     this_is_a_single_line_edit_box                              "This is a single line edit box. It uses fixed system font to display text"
#define     multiple_line_edit_box_using_variable_width_font            "Multiple-line edit box using variable-width font"
#define     multiple_line_edit_box_auto_wrap                            "Multiple-line edit box (auto-wrap):"
#define     password_edit_box                                           "Password edit box:"
#define     typed_chars_to_upper_case                                   "Typed chars to upper case:"
#define     typed_chars_to_lower_case                                   "Typed chars to lower case:"
#define     read_only_edit_box                                          "Read only edit box:"
#define     you_can_not_edit_the_text_in_this_edit_box                  "You can not edit the text in this edit box."
#define     limited_edit_box                                            "Limited edit box:"
#define     you_can_only_input_characters_in_box                        "You can only input 100 characters in this box."
#define     right_aligned_text                                          "Right-aligned text"
#define     center_aligned_text                                         "Center-aligned text"
#define     edit_controls                                               "Edit controls"

#define     a_normal_listbox_sorted                                     "A normal listbox (sorted)"
#define     files_in_the_current_direcotory                             "Files in the current direcotory"
#define     a_listbox_with_LBS_USEICON_style                            "A listbox with LBS_USEICON style:"
#define     files_in_the_current_direcotory                             "Files in the current direcotory"
#define     a_listbox_with_LBS_MULTIPLESEL_style                        "A listbox with LBS_MULTIPLESEL style:"
#define     files_in_the_current_direcotory                             "Files in the current direcotory"
#define     are_you_sure_to_delete_this_item                            "Are you sure to delete this item?"
#define     Listbox                                                     "Listbox"
#define     add_me_to_the_box_bellow                                    "Add me to the box bellow"
#define     Add                                                         "Add"
#define     Delete                                                      "Delete"
#define     Find                                                        "Find"
#define     one_initially_checked_item                                  "One initially checked item"
#define     one_initially_not_checked_item                              "One initially not checked item"
#define     one_initially_part_checked_item                             "One initially part-checked item"
#define     ListBox_controls                                            "ListBox controls"

#define     ProgressBar_controls                                        "ProgressBar controls"

#define     ComboBox_controls                                           "ComboBox controls"
#define     selected_                                                   "selected"
#define     Up                                                          "Up"
#define     Prev                                                        "Prev"
#define     Next                                                        "Next"
#define     Menu                                                        "Menu"
#define     NewToolBar_controls                                         "NewToolBar controls"
#define     Delete_the_selected_item                                    "Delete the selected item"
#define     Clear_all_item                                              "Clear all item"
#define     select_item                                                 "select item"
#define     show_item                                                   "show item"
#define     del_column                                                  "del column"
#define     set_column_head                                             "set column head"
#define     sorting_the_items                                           "sorting the items"
#define     find_item                                                   "find item"
#define     open                                                        "open"
#define     copy                                                        "copy"
#define     delete_                                                     "delete"
#define     rename                                                      "rename"
#define     properties                                                  "properties"
#define     are_you_really_want_to_delete_this_file                     "are you really want to delete this file?"
#define     warning                                                     "warning"
#define     Are_you_really_want_to_open_this_file                       "Are you really want to open this file?"
#define     Question                                                    "Question"
#define     File_name                                                   "File name"
#define     File_size                                                   "File size"
#define     Category                                                    "Category"
#define     Last_modified_time                                          "Last modified time"
#define     ListView_control                                            "ListView control"
#define     directory                                                   "directory"
#define     regular_file                                                "regular file"

#define     Add_a_child_to_current_node                                 "Add a child to current node."
#define     Find_a_node_in_treeview                                     "Find a node in treeview."
#define     Add                                                         "Add"
#define     Del                                                         "Del"
#define     Find                                                        "Find"
#define     TreeView_controls                                           "TreeView controls"

#define     monthcalendar                                               "monthcalendar"
#define     get_current_day                                             "get current day"
#define     get_current_month                                           "get current month"
#define     get_current_year                                            "get current year"
#define     set_current_day                                             "set current day"
#define     set_current_month                                           "set current month"
#define     set_current_year                                            "set current year"
#define     set_current_date_as_today                                   "set current date as today"
#define     get_first_day_of_week                                       "get first day of week"
#define     get_current_date                                            "get current date"
#define     get_today                                                   "get today"
#define     get_minreqrectsize                                          "get minreqrectsize"
#define     set_current_date                                            "set current date"
#define     set_color                                                   "set color"
#define     get_color                                                   "get color"
#define     MonthCalendar_control                                       "MonthCalendar control"

#define     About_SpinBox_control                                       "About SpinBox control"
#define     About_SpinBox_message   "We use the SpinBox control in this Help Message Box.\n\n"  \
                                    "You can click the up arrow of the control to scroll up "    \
                                    "the message, and click the down arrow of the control to scroll down. "  \
                                    "You can also scroll the message by typing ArrowDown and ArrowUp keys.\n\n" \
                                    "In your application, you can call 'myWinHelpMessage' function " \
                                    "to build a Help Message box like this.\n\n" \
                                    "The Help Message Box is useful for some PDA-like applications.\n\n" \
                                    "The SpinBox control allways have the fixed width and height. " \
                                    "You can read the source of 'ext/control/spinbox.c' to know how to " \
                                    "build such a control.\n\n" \
                                    "If you want to know how to use this control, please read the " \
                                    "source of 'mywindows/helpwin.c' in the MiniGUI source tree." 
#define     Digit_only_box          "Digit-only box:"
#define     Alpha_only_box          "Alpha-only box:"
#define     Normal_edit_box         "Normal edit box:"
#define     Subclass_of_Control     "Subclass of Control"


#define     property_caption        "Demo for Property Sheet"
#define     sure                    "OK"
#define     initializing            "VAM-CNC "
#define     doing                   "initializing..."
#define     please_select_mode      "mode"
#define     mode                    "mode"
#define     mode_mdi                "MDI"
#define     mode_bg                 "background process"
#define     mode_moving             "moving control"
#define     mode_param              "param setting"
#define     mode_helper             "auxiliary equipment"
#define     combox                  "combobox"
#define     prompt                  "MDI mode,process maually."

#define     machine_setting         "setting"
#define     fixpla_top_radius       "1.top radius of still platform"
#define     fixpla_bot_radius       "2.bottom radius of still platform"
#define     fixpla_height           "3.height of still platform"
#define     fixpla_angle            "4.angle of still platform"
#define     movepla_top_radius      "5.top radius of mobile platform"
#define     movepla_bot_radius      "6.bottom radius of mobile platform"
#define     movepla_height          "7.height of mobile platform"
#define     movepla_angle           "8.angle of mobile platform"
#define     platform_init_diff      "9.distance of angle"
#define     min_leg                 "A.minimum leg"
#define     max_leg                 "B.maximum leg"
#define     fixpla_distance         "C.distance between top and bottom"
#define     cancel                  "cancel"

#define     password_setting        "password" 
#define     enter_new_pwd           "please enter new password"
#define     pwd_valid               "valid password"

#define     apply                   "apply"
#define     time_caption            "Time Editor"
#define     time_editor             "This is a time editor.\n\n" \
                   "Pressing <Down-Arrow>, <Up-Arrow>, <PgDn>, and" \
                   " <PgUp> keys when the box has input focus will" \
                   " change the time.\n\n" \
                   "You can also change the time by clicking the SpinBox.\n"
#define      messageboxcap        "Waring!"
#define      messageboxinfo        "Please input something in the first edit box."
