#define     About                                      "關于"
#define     About_MiniGUI                              "關于 MiniGUI..."
#define     File                                       "文件"
#define     New                                        "新建"
#define     Open                                       "打開..."
#define     Save                                       "保存"
#define     Save_As                                    "另存為..."
#define     Close                                      "關閉"
#define     Exit                                       "退出"
#define     Dialogs                                    "對話框"
#define     Dialog1                                    "對話框1..."
#define     Dialog2                                    "對話框2..."
#define     Dialog3                                    "對話框3..."
#define     Dialog4                                    "對話框4..."
#define     Property_Sheet                             "表格..."
#define     Controls                                   "控件"
#define     Static_control                             "Static 控件"
#define     Button_control                             "Button 控件" 
#define     MenuButton_control                         "MenuButton 控件"
#define     Edit_control                               "Edit 控件"
#define     ListBox_control                            "ListBox 控件"
#define     ProgressBar_control                        "ProgressBar 控件"
#define     ComboBox_control                           "ComboBox 控件"
#define     NewToolBar_control                         "NewToolBar 控件"
#define     TrackBar_control                           "TrackBar 控件"
#define     ListView_control                           "ListView 控件"
#define     TreeView_control                           "TreeView 控件"
#define     MonthCalendar_control                      "MonthCalendar 控件"
#define     SpinBox_control                            "SpinBox 控件"
#define     CoolBar_control                            "CoolBar 控件"
#define     Control_Subclass                           "子控件"
#define     Time_Editor                                "時間編輯器"
#define     Are_you_sure_to_quit                       "确定要退出？"
#define     DlgTest                                    "對話框測識"
#define     The_dialog_and_control_demo                "對話框和控件"
#define     Push_Button                                "Push Button"
#define     Multiple_Lines_Push_Button                 "多行 Push Button"
#define     Normal_check_box                           "Normal check box"
#define     Normal_radio_button                        "Normal radio button"
#define     Auto_3_state_check_box                     "Auto 3-state check box"
#define     Auto_check_box_on_left                     "Auto check box on left"
#define     Push_like_check_box                        "Push-like check box"
#define     Auto_Radio_Button1                         "Auto Radio Button 1"
#define     Auto_Radio_Button2                         "Auto Radio Button 2"
#define     Auto_Radio_Button3                         "Auto Radio Button 3"
#define     Push_like_Radio1                           "Push-like Radio 1"
#define     Push_like_Radio2                           "Push-like Radio 2"
#define     Push_like_Radio3                           "Push-like Radio 3"
#define     Button_controls                            "Button 控件"
#define     This_is_a_simple_static_control            "這是 static 控件"
#define     This_is_a_left_aligned_static_control      "左對齊 static 控件 (auto-wrap)."
#define     This_is_a_right_aligned_static_control     "右對齊 static 控件 (auto-wrap)."
#define     This_is_a_center_aligned_static_control    "居中 static 控件 (auto-wrap)."
#define     An_icon_static_control                     "icon static 控件 "
#define     A_bitmap_static_control                    "bitmap static 控件"
#define     A_bitmap_static_control_center             "bitmap static 控件(center)"
#define     A_black_box                                "black box:"
#define     A_gray_box                                 "gray box:"
#define     A_white_box                                "white box:"
#define     A_black_frame                              "black frame:"
#define     A_gray_frame                               "gray frame:"
#define     A_white_frame                              "white frame:"
#define     A_Group_Box                                "Group Box"
#define     Tabs_are_expanded                          "SS_LEFTNOWORDWRAP: \tTabs are expanded,\
                                                             but words are not wrapped. "
#define     Static_controls                            "Static 控件"
#define     Files_in_the_current_directory             "當前路進下的文件"
#define     Files_and_directories_in_the_current_directory_sorted       "當前路進下的文件 (sorted)"
#define     Files_and_directories_in_the_current_directory              "當前路進下的文件 (sorted, bitmap)"
#define     MenuButton_controls                                         "MenuButton 控件"
#define     simple_edit_box_with_fixed_font                             "edit box 等寬字体"
#define     this_is_a_simple_edit_box                                   "這是 simple edit box. 用等寬字体顯示文字"
#define     single_line_edit_box_using_variable_width_font              "單行變寬字体 edit"
#define     this_is_a_single_line_edit_box                              "這是單行 edit box. 用變寬字体顯示文字"
#define     multiple_line_edit_box_using_variable_width_font            "多行 edit box 變寬字体"
#define     multiple_line_edit_box_auto_wrap                            "多行 edit box (auto-wrap):"
#define     password_edit_box                                           "密碼 edit box:"
#define     typed_chars_to_upper_case                                   "大寫字母:"
#define     typed_chars_to_lower_case                                   "小寫字母:"
#define     read_only_edit_box                                          "只讀 edit box:"
#define     you_can_not_edit_the_text_in_this_edit_box                  "這個 edit 是不可以編輯的"
#define     limited_edit_box                                            "輸入限制 edit box:"
#define     you_can_only_input_characters_in_box                        "在這個輸入框你可以輸入100個字母"
#define     right_aligned_text                                          "右對奇文字"
#define     center_aligned_text                                         "居中文字"
#define     edit_controls                                               "Edit 控件"

#define     a_normal_listbox_sorted                                     "listbox (sorted)"
#define     files_in_the_current_direcotory                             "所有文件"
#define     a_listbox_with_LBS_USEICON_style                            "listbox (LBS_USEICON)"
#define     a_listbox_with_LBS_MULTIPLESEL_style                        "listbox (LBS_MULTIPLESEL)"
#define     are_you_sure_to_delete_this_item                            "确信要刪除？"
#define     Listbox                                                     "Listbox"
#define     add_me_to_the_box_bellow                                    "添加"
#define     Add                                                         "添加"
#define     Delete                                                      "刪除"
#define     Find                                                        "查找"
#define     one_initially_checked_item                                  "默認選中"
#define     one_initially_not_checked_item                              "默認沒有選中"
#define     one_initially_part_checked_item                             "默認 part-checked "
#define     ListBox_controls                                            "ListBox 控件"

#define     ProgressBar_controls                                        "ProgressBar 控件"

#define     ComboBox_controls                                           "ComboBox 控件"
#define     selected_                                                   "選中"
#define     Up                                                          "上"
#define     Prev                                                        "前"
#define     Next                                                        "后"
#define     Menu                                                        "菜單"
#define     NewToolBar_controls                                         "NewToolBar 控件"
#define     Delete_the_selected_item                                    "刪除"
#define     Clear_all_item                                              "刪除所有"
#define     select_item                                                 "全選"
#define     show_item                                                   "顯示"
#define     del_column                                                  "刪除column"
#define     set_column_head                                             "設置column頭"
#define     sorting_the_items                                           "排序"
#define     find_item                                                   "查找"
#define     open                                                        "打開"
#define     copy                                                        "考貝"
#define     delete_                                                     "刪除"
#define     rename                                                      "重命名"
#define     properties                                                  "性能"
#define     are_you_really_want_to_delete_this_file                     "确定要刪除?"
#define     warning                                                     "警告"
#define     Are_you_really_want_to_open_this_file                       "想要打開這個文件嗎？"
#define     Question                                                    "問提"
#define     File_name                                                   "文件名"
#define     File_size                                                   "文件大小"
#define     Category                                                    "類別"
#define     Last_modified_time                                          "最后修改日期"
#define     ListView_control                                            "ListView 控件"
#define     directory                                                   "字典"
#define     regular_file                                                "普通文件"

#define     Add_a_child_to_current_node                                 "添加一個節點"
#define     Find_a_node_in_treeview                                     "查找一個節點"
#define     Add                                                         "添加"
#define     Del                                                         "刪除"
#define     Find                                                        "查找"
#define     TreeView_controls                                           "TreeView 控件"

#define     monthcalendar                                               "monthcalendar"
#define     get_current_day                                             "日"
#define     get_current_month                                           "月"
#define     get_current_year                                            "年"
#define     set_current_day                                             "設置日"
#define     set_current_month                                           "設置月"
#define     set_current_year                                            "設置年"
#define     set_current_date_as_today                                   "設置日期"
#define     get_first_day_of_week                                       "哲星期第一天"
#define     get_current_date                                            "當前日期"
#define     get_today                                                   "今天"
#define     get_minreqrectsize                                          " minreqrectsize"
#define     set_current_date                                            "設置日期"
#define     set_color                                                   "設置顏色"
#define     get_color                                                   "提取顏色"
#define     MonthCalendar_control                                       "MonthCalendar 控件"

#define     About_SpinBox_control                                       "關于 SpinBox 控件"
#define     About_SpinBox_message   "We use the SpinBox control in this Help Message Box.\n\n"  \
                                    "You can click the up arrow of the control to scroll up "    \
                                    "the message, and click the down arrow of the control to scroll down. "  \
                                    "You can also scroll the message by typing ArrowDown and ArrowUp keys.\n\n" \
                                    "In your application, you can call 'myWinHelpMessage' function " \
                                    "to build a Help Message box like this.\n\n" \
                                    "The Help Message Box is useful for some PDA-like applications.\n\n" \
                                    "The SpinBox control allways have the fixed width and height. " \
                                    "You can read the source of 'ext/control/spinbox.c' to know how to " \
                                    "build such a control.\n\n" \
                                    "If you want to know how to use this control, please read the " \
                                    "source of 'mywindows/helpwin.c' in the MiniGUI source tree." 

#define     Digit_only_box          "數字 box:"
#define     Alpha_only_box          "字母 box:"
#define     Normal_edit_box         "普通 edit box:"
#define     Subclass_of_Control     "子控件"

#define     property_caption        "屬性頁示例"
#define     sure                    "确定"
#define     initializing            "VAM-CNC"
#define     doing                   "正在進行初始化..."
#define     please_select_mode      "請選擇工作模式"
#define     mode                    "工作模式"
#define     mode_mdi                "MDI 方式"
#define     mode_bg                 "后台處理"
#define     mode_moving             "運動控制"
#define     mode_param              "參數設置"
#define     mode_helper             "輔助設憊"
#define     combox                  "combobox"
#define     prompt                  "MDI 方式，手工編程。"

#define     machine_setting         "机床參數設置"
#define     fixpla_top_radius       "1.靜止平台上正三角形外接圓半徑"
#define     fixpla_bot_radius       "2.靜止平台下正三角形外接圓半徑"
#define     fixpla_height           "3.靜止平台上下正三角形高差"
#define     fixpla_angle            "4.靜止平台上下正三角形度差"
#define     movepla_top_radius      "5.動平台上正三角形外接圓半徑"
#define     movepla_bot_radius      "6.動平台下正三角形外接圓半徑"
#define     movepla_height          "7.動平台上下正三角形高差"
#define     movepla_angle           "8.動平台上下正三角形度差"
#define     platform_init_diff      "9.動靜平台在初始位置時的度差"
#define     min_leg                 "A.机床最小腿長"
#define     max_leg                 "B.机床最大腿長"
#define     fixpla_distance         "C.上下靜止平台之間的距离"
#define     cancel                  "取消"

#define     password_setting        "系統管理員口令設置" 
#define     enter_new_pwd           "請輸入新的口令"
#define     pwd_valid               "密碼有效"

#define     apply                   "應用"
#define     time_caption            "時間編輯器"
#define     time_editor             "這是時間編輯器。\n\n" \
                    "有輸入焦點之后，可以通過按鍵 <Down-Arrow>， <Up-Arrow>， <PgDn>， 和 <PgUp> " \
                    "來修改時間。\n\n" \
                    "也可以通過點擊旋鈕控件來修改時間。\n"
#define      messageboxcap        "警告！"
#define      messageboxinfo        "請在第一個編輯框內輸入信息。"

