#define please_input_the_length                      "請輸入長度"
#define please_input_the_length_mm                   "請輸入長度（單位：毫米）"
#define equivalent_to_inches                         "相當於0.00英寸"
#define OK                                           "確定"
#define equivalent_to_f_inches                       "相當於%.5f英寸"
