#define deleting_the_files 	"刪除文件"
#define directories 				"路徑:"
#define files_ 					"文件:"
#define path_ 						"在: "
#define delete_ 					"刪除"
#define cancel_ 					"取消"
#define deleting_files_ 		"刪除文件"
