/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.32                      *
*        Compiled Oct  8 2015, 11:58:55                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: NVTFont16.c                                           *
* Font:        <unknown>                                             *
* Height:      16                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  16                                           *
* Range disabled:       0000 - FFFF                                  *
* Range enabled:        0000 - 007F                                  *
* Character enabled:   0x7D50 (32080)                                *
* Edit/Insert/Right     at character 0x7D50 (32080)                  *
* Edit/Insert/Right     at character 0x7D50 (32080)                  *
* Edit/Insert/Right     at character 0x7D50 (32080)                  *
* Edit/Insert/Right     at character 0x7D50 (32080)                  *
* Edit/Insert/Right     at character 0x7D50 (32080)                  *
* Edit/Insert/Right     at character 0x7D50 (32080)                  *
* Edit/Insert/Right     at character 0x7D50 (32080)                  *
* Edit/Insert/Right     at character 0x7D50 (32080)                  *
* Edit/Insert/Right     at character 0x7D50 (32080)                  *
* Edit/Insert/Right     at character 0x7D50 (32080)                  *
* Edit/Insert/Right     at character 0x7D50 (32080)                  *
* Edit/Insert/Right     at character 0x7D50 (32080)                  *
* Edit/Insert/Right     at character 0x7D50 (32080)                  *
* Edit/Insert/Right     at character 0x7D50 (32080)                  *
* Edit/Insert/Right     at character 0x7D50 (32080)                  *
* Edit/Insert/Right     at character 0x7D50 (32080)                  *
* Edit/Insert/Right     at character 0x7D50 (32080)                  *
* Edit/Insert/Right     at character 0x7D50 (32080)                  *
* Edit/Insert/Right     at character 0x7D50 (32080)                  *
* Edit/Insert/Right     at character 0x7D50 (32080)                  *
* Edit/Insert/Right     at character 0x7D50 (32080)                  *
* Pixel index of character 0x7D50 (32080) at 5/4 set to 1            *
* Pixel index of character 0x7D50 (32080) at 4/5 set to 1            *
* Pixel index of character 0x7D50 (32080) at 3/6 set to 1            *
* Pixel index of character 0x7D50 (32080) at 2/7 set to 1            *
* Pixel index of character 0x7D50 (32080) at 3/8 set to 1            *
* Pixel index of character 0x7D50 (32080) at 4/9 set to 1            *
* Pixel index of character 0x7D50 (32080) at 5/8 set to 1            *
* Pixel index of character 0x7D50 (32080) at 6/7 set to 1            *
* Pixel index of character 0x7D50 (32080) at 7/6 set to 1            *
* Pixel index of character 0x7D50 (32080) at 3/10 set to 1           *
* Pixel index of character 0x7D50 (32080) at 2/11 set to 1           *
* Pixel index of character 0x7D50 (32080) at 3/11 set to 1           *
* Pixel index of character 0x7D50 (32080) at 4/11 set to 1           *
* Pixel index of character 0x7D50 (32080) at 5/11 set to 1           *
* Pixel index of character 0x7D50 (32080) at 6/10 set to 1           *
* Pixel index of character 0x7D50 (32080) at 6/11 set to 1           *
* Pixel index of character 0x7D50 (32080) at 7/11 set to 1           *
* Pixel index of character 0x7D50 (32080) at 8/12 set to 1           *
* Pixel index of character 0x7D50 (32080) at 7/11 set to 0           *
* Pixel index of character 0x7D50 (32080) at 7/12 set to 1           *
* Pixel index of character 0x7D50 (32080) at 7/10 set to 1           *
* Pixel index of character 0x7D50 (32080) at 7/9 set to 1            *
* Pixel index of character 0x7D50 (32080) at 8/10 set to 1           *
* Pixel index of character 0x7D50 (32080) at 9/11 set to 1           *
* Pixel index of character 0x7D50 (32080) at 7/12 set to 0           *
* Pixel index of character 0x7D50 (32080) at 8/12 set to 0           *
* Pixel index of character 0x7D50 (32080) at 2/13 set to 1           *
* Pixel index of character 0x7D50 (32080) at 2/14 set to 1           *
* Pixel index of character 0x7D50 (32080) at 4/13 set to 1           *
* Pixel index of character 0x7D50 (32080) at 4/14 set to 1           *
* Pixel index of character 0x7D50 (32080) at 6/13 set to 1           *
* Pixel index of character 0x7D50 (32080) at 6/14 set to 1           *
* Pixel index of character 0x7D50 (32080) at 11/5 set to 1           *
* Pixel index of character 0x7D50 (32080) at 12/5 set to 1           *
* Pixel index of character 0x7D50 (32080) at 12/5 set to 0           *
* Pixel index of character 0x7D50 (32080) at 12/5 set to 1           *
* Pixel index of character 0x7D50 (32080) at 13/5 set to 1           *
* Pixel index of character 0x7D50 (32080) at 14/5 set to 1           *
* Pixel index of character 0x7D50 (32080) at 15/5 set to 1           *
* Pixel index of character 0x7D50 (32080) at 16/5 set to 1           *
* Pixel index of character 0x7D50 (32080) at 17/5 set to 1           *
* Pixel index of character 0x7D50 (32080) at 11/7 set to 1           *
* Pixel index of character 0x7D50 (32080) at 13/7 set to 1           *
* Pixel index of character 0x7D50 (32080) at 12/7 set to 1           *
* Pixel index of character 0x7D50 (32080) at 14/7 set to 1           *
* Pixel index of character 0x7D50 (32080) at 15/7 set to 1           *
* Pixel index of character 0x7D50 (32080) at 16/7 set to 1           *
* Pixel index of character 0x7D50 (32080) at 17/7 set to 1           *
* Pixel index of character 0x7D50 (32080) at 13/6 set to 1           *
* Pixel index of character 0x7D50 (32080) at 13/4 set to 1           *
* Pixel index of character 0x7D50 (32080) at 16/5 set to 0           *
* Pixel index of character 0x7D50 (32080) at 17/5 set to 0           *
* Pixel index of character 0x7D50 (32080) at 16/7 set to 0           *
* Pixel index of character 0x7D50 (32080) at 17/7 set to 0           *
* Pixel index of character 0x7D50 (32080) at 11/9 set to 1           *
* Pixel index of character 0x7D50 (32080) at 12/9 set to 1           *
* Pixel index of character 0x7D50 (32080) at 13/9 set to 1           *
* Pixel index of character 0x7D50 (32080) at 14/9 set to 1           *
* Pixel index of character 0x7D50 (32080) at 15/9 set to 1           *
* Pixel index of character 0x7D50 (32080) at 15/10 set to 1          *
* Pixel index of character 0x7D50 (32080) at 15/11 set to 1          *
* Pixel index of character 0x7D50 (32080) at 15/12 set to 1          *
* Pixel index of character 0x7D50 (32080) at 14/12 set to 1          *
* Pixel index of character 0x7D50 (32080) at 13/12 set to 1          *
* Pixel index of character 0x7D50 (32080) at 12/12 set to 1          *
* Pixel index of character 0x7D50 (32080) at 11/12 set to 1          *
* Pixel index of character 0x7D50 (32080) at 11/11 set to 1          *
* Pixel index of character 0x7D50 (32080) at 11/10 set to 1          *
* Pixel index of character 0x7D50 (32080) at 8/10 set to 0           *
* Pixel index of character 0x7D50 (32080) at 4/4 set to 1            *
* Pixel index of character 0x7D50 (32080) at 3/5 set to 1            *
* Pixel index of character 0x7D50 (32080) at 2/6 set to 1            *
* Pixel index of character 0x7D50 (32080) at 1/7 set to 1            *
* Pixel index of character 0x7D50 (32080) at 2/8 set to 1            *
* Pixel index of character 0x7D50 (32080) at 6/6 set to 1            *
* Pixel index of character 0x7D50 (32080) at 5/7 set to 1            *
* Pixel index of character 0x7D50 (32080) at 4/8 set to 1            *
* Pixel index of character 0x7D50 (32080) at 8/10 set to 1           *
* Pixel index of character 0x7D50 (32080) at 8/11 set to 1           *
* Pixel index of character 0x7D50 (32080) at 6/14 set to 0           *
* Pixel index of character 0x7D50 (32080) at 4/14 set to 0           *
* Pixel index of character 0x7D50 (32080) at 2/14 set to 0           *
* Pixel index of character 0x7D50 (32080) at 10/5 set to 1           *
* Pixel index of character 0x7D50 (32080) at 16/5 set to 1           *
* Pixel index of character 0x7D50 (32080) at 16/7 set to 1           *
* Pixel index of character 0x7D50 (32080) at 10/7 set to 1           *
* Pixel index of character 0x7D50 (32080) at 16/9 set to 1           *
* Pixel index of character 0x7D50 (32080) at 16/10 set to 1          *
* Pixel index of character 0x7D50 (32080) at 16/11 set to 1          *
* Pixel index of character 0x7D50 (32080) at 16/12 set to 1          *
* Pixel index of character 0x7D50 (32080) at 15/11 set to 0          *
* Pixel index of character 0x7D50 (32080) at 15/10 set to 0          *
*                                                                    *
**********************************************************************
*                                                                    *
* Character enabled:   0x679C (26524)                                *
* Edit/Insert/Right     at character 0x679C (26524)                  *
* Edit/Insert/Right     at character 0x679C (26524)                  *
* Edit/Insert/Right     at character 0x679C (26524)                  *
* Edit/Insert/Right     at character 0x679C (26524)                  *
* Edit/Insert/Right     at character 0x679C (26524)                  *
* Edit/Insert/Right     at character 0x679C (26524)                  *
* Edit/Insert/Right     at character 0x679C (26524)                  *
* Edit/Insert/Right     at character 0x679C (26524)                  *
* Edit/Insert/Right     at character 0x679C (26524)                  *
* Edit/Insert/Right     at character 0x679C (26524)                  *
* Edit/Insert/Right     at character 0x679C (26524)                  *
* Edit/Insert/Right     at character 0x679C (26524)                  *
* Edit/Insert/Right     at character 0x679C (26524)                  *
* Edit/Insert/Right     at character 0x679C (26524)                  *
* Edit/Insert/Right     at character 0x679C (26524)                  *
* Edit/Insert/Right     at character 0x679C (26524)                  *
* Edit/Insert/Right     at character 0x679C (26524)                  *
* Edit/Insert/Right     at character 0x679C (26524)                  *
* Edit/Insert/Right     at character 0x679C (26524)                  *
* Edit/Insert/Right     at character 0x679C (26524)                  *
* Edit/Insert/Right     at character 0x679C (26524)                  *
* Pixel index of character 0x679C (26524) at 6/3 set to 1            *
* Pixel index of character 0x679C (26524) at 7/3 set to 1            *
* Pixel index of character 0x679C (26524) at 8/3 set to 1            *
* Pixel index of character 0x679C (26524) at 9/3 set to 1            *
* Pixel index of character 0x679C (26524) at 10/3 set to 1           *
* Pixel index of character 0x679C (26524) at 11/3 set to 1           *
* Pixel index of character 0x679C (26524) at 12/3 set to 1           *
* Pixel index of character 0x679C (26524) at 13/3 set to 1           *
* Pixel index of character 0x679C (26524) at 14/3 set to 1           *
* Pixel index of character 0x679C (26524) at 14/4 set to 1           *
* Pixel index of character 0x679C (26524) at 14/5 set to 1           *
* Pixel index of character 0x679C (26524) at 14/6 set to 1           *
* Pixel index of character 0x679C (26524) at 14/7 set to 1           *
* Pixel index of character 0x679C (26524) at 14/8 set to 1           *
* Pixel index of character 0x679C (26524) at 13/5 set to 1           *
* Pixel index of character 0x679C (26524) at 12/5 set to 1           *
* Pixel index of character 0x679C (26524) at 11/5 set to 1           *
* Pixel index of character 0x679C (26524) at 10/5 set to 1           *
* Pixel index of character 0x679C (26524) at 9/5 set to 1            *
* Pixel index of character 0x679C (26524) at 8/5 set to 1            *
* Pixel index of character 0x679C (26524) at 7/5 set to 1            *
* Pixel index of character 0x679C (26524) at 6/5 set to 1            *
* Pixel index of character 0x679C (26524) at 6/4 set to 1            *
* Pixel index of character 0x679C (26524) at 6/6 set to 1            *
* Pixel index of character 0x679C (26524) at 6/7 set to 1            *
* Pixel index of character 0x679C (26524) at 8/7 set to 1            *
* Pixel index of character 0x679C (26524) at 7/7 set to 1            *
* Pixel index of character 0x679C (26524) at 9/7 set to 1            *
* Pixel index of character 0x679C (26524) at 10/7 set to 1           *
* Pixel index of character 0x679C (26524) at 11/7 set to 1           *
* Pixel index of character 0x679C (26524) at 12/7 set to 1           *
* Pixel index of character 0x679C (26524) at 13/7 set to 1           *
* Pixel index of character 0x679C (26524) at 14/8 set to 0           *
* Pixel index of character 0x679C (26524) at 13/4 set to 1           *
* Pixel index of character 0x679C (26524) at 13/6 set to 1           *
* Pixel index of character 0x679C (26524) at 14/3 set to 0           *
* Pixel index of character 0x679C (26524) at 14/4 set to 0           *
* Pixel index of character 0x679C (26524) at 14/5 set to 0           *
* Pixel index of character 0x679C (26524) at 14/6 set to 0           *
* Pixel index of character 0x679C (26524) at 14/7 set to 0           *
* Pixel index of character 0x679C (26524) at 9/4 set to 1            *
* Pixel index of character 0x679C (26524) at 9/6 set to 1            *
* Pixel index of character 0x679C (26524) at 5/3 set to 1            *
* Pixel index of character 0x679C (26524) at 5/4 set to 1            *
* Pixel index of character 0x679C (26524) at 5/5 set to 1            *
* Pixel index of character 0x679C (26524) at 5/6 set to 1            *
* Pixel index of character 0x679C (26524) at 5/7 set to 1            *
* Pixel index of character 0x679C (26524) at 6/6 set to 0            *
* Pixel index of character 0x679C (26524) at 6/4 set to 0            *
* Pixel index of character 0x679C (26524) at 3/9 set to 1            *
* Pixel index of character 0x679C (26524) at 4/9 set to 1            *
* Pixel index of character 0x679C (26524) at 5/9 set to 1            *
* Pixel index of character 0x679C (26524) at 6/9 set to 1            *
* Pixel index of character 0x679C (26524) at 7/9 set to 1            *
* Pixel index of character 0x679C (26524) at 8/9 set to 1            *
* Pixel index of character 0x679C (26524) at 9/9 set to 1            *
* Pixel index of character 0x679C (26524) at 10/9 set to 1           *
* Pixel index of character 0x679C (26524) at 11/9 set to 1           *
* Pixel index of character 0x679C (26524) at 12/9 set to 1           *
* Pixel index of character 0x679C (26524) at 13/9 set to 1           *
* Pixel index of character 0x679C (26524) at 14/9 set to 1           *
* Pixel index of character 0x679C (26524) at 15/9 set to 1           *
* Pixel index of character 0x679C (26524) at 9/8 set to 1            *
* Pixel index of character 0x679C (26524) at 9/9 set to 0            *
* Pixel index of character 0x679C (26524) at 9/10 set to 1           *
* Pixel index of character 0x679C (26524) at 9/9 set to 1            *
* Pixel index of character 0x679C (26524) at 9/11 set to 1           *
* Pixel index of character 0x679C (26524) at 9/12 set to 1           *
* Pixel index of character 0x679C (26524) at 9/13 set to 1           *
* Pixel index of character 0x679C (26524) at 9/14 set to 1           *
* Pixel index of character 0x679C (26524) at 8/10 set to 1           *
* Pixel index of character 0x679C (26524) at 7/11 set to 1           *
* Pixel index of character 0x679C (26524) at 6/13 set to 1           *
* Pixel index of character 0x679C (26524) at 6/14 set to 1           *
* Pixel index of character 0x679C (26524) at 6/14 set to 0           *
* Pixel index of character 0x679C (26524) at 6/13 set to 0           *
* Pixel index of character 0x679C (26524) at 6/12 set to 1           *
* Pixel index of character 0x679C (26524) at 5/13 set to 1           *
* Pixel index of character 0x679C (26524) at 4/14 set to 1           *
* Pixel index of character 0x679C (26524) at 10/10 set to 1          *
* Pixel index of character 0x679C (26524) at 11/11 set to 1          *
* Pixel index of character 0x679C (26524) at 12/12 set to 1          *
* Pixel index of character 0x679C (26524) at 13/13 set to 1          *
* Pixel index of character 0x679C (26524) at 14/14 set to 1          *
*                                                                    *
**********************************************************************
  C-file modified by emWin Font Converter (ST) version 5.32: Jan 31 2018 at 11:36:35
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
#define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontNVTFont16;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_0020[ 16] =   /* code 0020, SPACE */
{
    ________,
    ________,
    ________,
    ________,
    ________,
    ________,
    ________,
    ________,
    ________,
    ________,
    ________,
    ________,
    ________,
    ________,
    ________,
    ________
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_0021[ 16] =   /* code 0021, EXCLAMATION MARK */
{
    ________,
    ________,
    ________,
    _X______,
    _X______,
    _X______,
    _X______,
    _X______,
    _X______,
    _X______,
    _X______,
    ________,
    _X______,
    ________,
    ________,
    ________
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_0022[ 16] =   /* code 0022, QUOTATION MARK */
{
    ________,
    ________,
    ________,
    _X_X____,
    _X_X____,
    _X_X____,
    ________,
    ________,
    ________,
    ________,
    ________,
    ________,
    ________,
    ________,
    ________,
    ________
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_0023[ 16] =   /* code 0023, NUMBER SIGN */
{
    ________,
    ________,
    ________,
    ___X__X_,
    ___X__X_,
    __X___X_,
    XXXXXXX_,
    __X__X__,
    __X__X__,
    XXXXXXX_,
    _X__X___,
    _X__X___,
    _X__X___,
    ________,
    ________,
    ________
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_0024[ 16] =   /* code 0024, DOLLAR SIGN */
{
    ________,
    ________,
    ________,
    __XXX___,
    _X_X_X__,
    _X_X____,
    _X_X____,
    _XXX____,
    ___XXX__,
    ___X_X__,
    _X_X_X__,
    _X_X_X__,
    __XXX___,
    ___X____,
    ________,
    ________
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_0025[ 32] =   /* code 0025, PERCENT SIGN */
{
    ________,________,
    ________,________,
    ________,________,
    __XX____,X_______,
    _X__X__X,________,
    _X__X__X,________,
    _X__X_X_,________,
    __XX__X_,________,
    _____X__,XX______,
    _____X_X,__X_____,
    ____X__X,__X_____,
    ____X__X,__X_____,
    ___X____,XX______,
    ________,________,
    ________,________,
    ________,________
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_0026[ 32] =   /* code 0026, AMPERSAND */
{
    ________,________,
    ________,________,
    ________,________,
    ___XX___,________,
    __X__X__,________,
    __X__X__,________,
    __X__X__,________,
    ___XX___,________,
    __XX____,________,
    _X__X__X,________,
    _X___X_X,________,
    _X___XX_,________,
    __XXX__X,X_______,
    ________,________,
    ________,________,
    ________,________
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_0027[ 16] =   /* code 0027, APOSTROPHE */
{
    ________,
    ________,
    ________,
    _X______,
    _X______,
    _X______,
    ________,
    ________,
    ________,
    ________,
    ________,
    ________,
    ________,
    ________,
    ________,
    ________
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_0028[ 16] =   /* code 0028, LEFT PARENTHESIS */
{
    ________,
    ________,
    ________,
    ___X____,
    __X_____,
    __X_____,
    _X______,
    _X______,
    _X______,
    _X______,
    _X______,
    _X______,
    _X______,
    __X_____,
    __X_____,
    ___X____
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_0029[ 16] =   /* code 0029, RIGHT PARENTHESIS */
{
    ________,
    ________,
    ________,
    X_______,
    _X______,
    _X______,
    __X_____,
    __X_____,
    __X_____,
    __X_____,
    __X_____,
    __X_____,
    __X_____,
    _X______,
    _X______,
    X_______
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_002A[ 16] =   /* code 002A, ASTERISK */
{
    ________,
    ________,
    ________,
    __X_____,
    XXXXX___,
    __X_____,
    _X_X____,
    ________,
    ________,
    ________,
    ________,
    ________,
    ________,
    ________,
    ________,
    ________
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_002B[ 16] =   /* code 002B, PLUS SIGN */
{
    ________,
    ________,
    ________,
    ________,
    ________,
    ____X___,
    ____X___,
    ____X___,
    _XXXXXXX,
    ____X___,
    ____X___,
    ____X___,
    ________,
    ________,
    ________,
    ________
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_002C[ 16] =   /* code 002C, COMMA */
{
    ________,
    ________,
    ________,
    ________,
    ________,
    ________,
    ________,
    ________,
    ________,
    ________,
    ________,
    ________,
    __X_____,
    __X_____,
    __X_____,
    ________
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_002D[ 16] =   /* code 002D, HYPHEN-MINUS */
{
    ________,
    ________,
    ________,
    ________,
    ________,
    ________,
    ________,
    ________,
    ________,
    XXX_____,
    ________,
    ________,
    ________,
    ________,
    ________,
    ________
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_002E[ 16] =   /* code 002E, FULL STOP */
{
    ________,
    ________,
    ________,
    ________,
    ________,
    ________,
    ________,
    ________,
    ________,
    ________,
    ________,
    ________,
    _X______,
    ________,
    ________,
    ________
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_002F[ 16] =   /* code 002F, SOLIDUS */
{
    ________,
    ________,
    ________,
    ___X____,
    ___X____,
    __X_____,
    __X_____,
    __X_____,
    _X______,
    _X______,
    _X______,
    X_______,
    X_______,
    ________,
    ________,
    ________
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_0030[ 16] =   /* code 0030, DIGIT ZERO */
{
    ________,
    ________,
    ________,
    _XXXX___,
    X____X__,
    X____X__,
    X____X__,
    X____X__,
    X____X__,
    X____X__,
    X____X__,
    X____X__,
    _XXXX___,
    ________,
    ________,
    ________
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_0031[ 16] =   /* code 0031, DIGIT ONE */
{
    ________,
    ________,
    ________,
    ___X____,
    __XX____,
    _X_X____,
    ___X____,
    ___X____,
    ___X____,
    ___X____,
    ___X____,
    ___X____,
    ___X____,
    ________,
    ________,
    ________
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_0032[ 16] =   /* code 0032, DIGIT TWO */
{
    ________,
    ________,
    ________,
    _XXXX___,
    X____X__,
    _____X__,
    _____X__,
    _____X__,
    ____X___,
    ___X____,
    __X_____,
    _X______,
    XXXXXX__,
    ________,
    ________,
    ________
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_0033[ 16] =   /* code 0033, DIGIT THREE */
{
    ________,
    ________,
    ________,
    _XXXX___,
    X____X__,
    _____X__,
    _____X__,
    __XXX___,
    _____X__,
    _____X__,
    _____X__,
    X____X__,
    _XXXX___,
    ________,
    ________,
    ________
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_0034[ 16] =   /* code 0034, DIGIT FOUR */
{
    ________,
    ________,
    ________,
    ____X___,
    ___XX___,
    ___XX___,
    __X_X___,
    __X_X___,
    _X__X___,
    _X__X___,
    XXXXXX__,
    ____X___,
    ____X___,
    ________,
    ________,
    ________
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_0035[ 16] =   /* code 0035, DIGIT FIVE */
{
    ________,
    ________,
    ________,
    _XXXXX__,
    _X______,
    _X______,
    X_______,
    XXXXX___,
    X____X__,
    _____X__,
    _____X__,
    X____X__,
    _XXXX___,
    ________,
    ________,
    ________
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_0036[ 16] =   /* code 0036, DIGIT SIX */
{
    ________,
    ________,
    ________,
    _XXXX___,
    X____X__,
    X_______,
    X_______,
    X_XXX___,
    XX___X__,
    X____X__,
    X____X__,
    X____X__,
    _XXXX___,
    ________,
    ________,
    ________
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_0037[ 16] =   /* code 0037, DIGIT SEVEN */
{
    ________,
    ________,
    ________,
    XXXXXX__,
    ____X___,
    ____X___,
    ___X____,
    ___X____,
    __X_____,
    __X_____,
    _X______,
    _X______,
    _X______,
    ________,
    ________,
    ________
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_0038[ 16] =   /* code 0038, DIGIT EIGHT */
{
    ________,
    ________,
    ________,
    _XXXX___,
    X____X__,
    X____X__,
    X____X__,
    _XXXX___,
    X____X__,
    X____X__,
    X____X__,
    X____X__,
    _XXXX___,
    ________,
    ________,
    ________
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_0039[ 16] =   /* code 0039, DIGIT NINE */
{
    ________,
    ________,
    ________,
    _XXXX___,
    X____X__,
    X____X__,
    X____X__,
    X___XX__,
    _XXX_X__,
    _____X__,
    _____X__,
    X___X___,
    _XXX____,
    ________,
    ________,
    ________
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_003A[ 16] =   /* code 003A, COLON */
{
    ________,
    ________,
    ________,
    ________,
    ________,
    ________,
    _X______,
    ________,
    ________,
    ________,
    ________,
    ________,
    _X______,
    ________,
    ________,
    ________
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_003B[ 16] =   /* code 003B, SEMICOLON */
{
    ________,
    ________,
    ________,
    ________,
    ________,
    ________,
    _X______,
    ________,
    ________,
    ________,
    ________,
    ________,
    _X______,
    _X______,
    _X______,
    ________
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_003C[ 16] =   /* code 003C, LESS-THAN SIGN */
{
    ________,
    ________,
    ________,
    ________,
    ________,
    ______X_,
    ____XX__,
    __XX____,
    _X______,
    __XX____,
    ____XX__,
    ______X_,
    ________,
    ________,
    ________,
    ________
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_003D[ 16] =   /* code 003D, EQUALS SIGN */
{
    ________,
    ________,
    ________,
    ________,
    ________,
    ________,
    XXXXXXX_,
    ________,
    ________,
    XXXXXXX_,
    ________,
    ________,
    ________,
    ________,
    ________,
    ________
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_003E[ 16] =   /* code 003E, GREATER-THAN SIGN */
{
    ________,
    ________,
    ________,
    ________,
    ________,
    _X______,
    __XX____,
    ____XX__,
    ______X_,
    ____XX__,
    __XX____,
    _X______,
    ________,
    ________,
    ________,
    ________
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_003F[ 16] =   /* code 003F, QUESTION MARK */
{
    ________,
    ________,
    ________,
    __XXX___,
    _X___X__,
    _X___X__,
    _____X__,
    ____X___,
    ___X____,
    __X_____,
    __X_____,
    ________,
    __X_____,
    ________,
    ________,
    ________
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_0040[ 32] =   /* code 0040, COMMERCIAL AT */
{
    ________,________,
    ________,________,
    ________,________,
    ____XXXX,X_______,
    __XX____,_X______,
    _X______,__X_____,
    _X__XXX_,X__X____,
    X__X___X,X__X____,
    X_X_____,X__X____,
    X_X____X,___X____,
    X_X____X,__X_____,
    X_X___XX,__X_____,
    X__XXX_X,XX______,
    _X______,___X____,
    __X_____,_XX_____,
    ___XXXXX,X_______
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_0041[ 32] =   /* code 0041, LATIN CAPITAL LETTER A */
{
    ________,________,
    ________,________,
    ________,________,
    ____X___,________,
    ___X_X__,________,
    ___X_X__,________,
    ___X_X__,________,
    __X___X_,________,
    __X___X_,________,
    _XXXXXXX,________,
    _X_____X,________,
    X_______,X_______,
    X_______,X_______,
    ________,________,
    ________,________,
    ________,________
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_0042[ 32] =   /* code 0042, LATIN CAPITAL LETTER B */
{
    ________,________,
    ________,________,
    ________,________,
    _XXXXXX_,________,
    _X_____X,________,
    _X_____X,________,
    _X_____X,________,
    _XXXXXX_,________,
    _X_____X,________,
    _X_____X,________,
    _X_____X,________,
    _X_____X,________,
    _XXXXXX_,________,
    ________,________,
    ________,________,
    ________,________
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_0043[ 32] =   /* code 0043, LATIN CAPITAL LETTER C */
{
    ________,________,
    ________,________,
    ________,________,
    ___XXX__,________,
    __X___X_,________,
    _X_____X,________,
    _X______,________,
    _X______,________,
    _X______,________,
    _X______,________,
    _X_____X,________,
    __X___X_,________,
    ___XXX__,________,
    ________,________,
    ________,________,
    ________,________
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_0044[ 32] =   /* code 0044, LATIN CAPITAL LETTER D */
{
    ________,________,
    ________,________,
    ________,________,
    _XXXXX__,________,
    _X____X_,________,
    _X_____X,________,
    _X_____X,________,
    _X_____X,________,
    _X_____X,________,
    _X_____X,________,
    _X_____X,________,
    _X____X_,________,
    _XXXXX__,________,
    ________,________,
    ________,________,
    ________,________
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_0045[ 32] =   /* code 0045, LATIN CAPITAL LETTER E */
{
    ________,________,
    ________,________,
    ________,________,
    _XXXXXXX,________,
    _X______,________,
    _X______,________,
    _X______,________,
    _XXXXXXX,________,
    _X______,________,
    _X______,________,
    _X______,________,
    _X______,________,
    _XXXXXXX,________,
    ________,________,
    ________,________,
    ________,________
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_0046[ 16] =   /* code 0046, LATIN CAPITAL LETTER F */
{
    ________,
    ________,
    ________,
    _XXXXXX_,
    _X______,
    _X______,
    _X______,
    _XXXXX__,
    _X______,
    _X______,
    _X______,
    _X______,
    _X______,
    ________,
    ________,
    ________
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_0047[ 32] =   /* code 0047, LATIN CAPITAL LETTER G */
{
    ________,________,
    ________,________,
    ________,________,
    ___XXXX_,________,
    __X____X,________,
    _X______,X_______,
    _X______,________,
    _X______,________,
    _X___XXX,X_______,
    _X______,X_______,
    _X______,X_______,
    __X____X,________,
    ___XXXX_,________,
    ________,________,
    ________,________,
    ________,________
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_0048[ 32] =   /* code 0048, LATIN CAPITAL LETTER H */
{
    ________,________,
    ________,________,
    ________,________,
    _X_____X,________,
    _X_____X,________,
    _X_____X,________,
    _X_____X,________,
    _XXXXXXX,________,
    _X_____X,________,
    _X_____X,________,
    _X_____X,________,
    _X_____X,________,
    _X_____X,________,
    ________,________,
    ________,________,
    ________,________
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_0049[ 16] =   /* code 0049, LATIN CAPITAL LETTER I */
{
    ________,
    ________,
    ________,
    _X______,
    _X______,
    _X______,
    _X______,
    _X______,
    _X______,
    _X______,
    _X______,
    _X______,
    _X______,
    ________,
    ________,
    ________
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_004A[ 16] =   /* code 004A, LATIN CAPITAL LETTER J */
{
    ________,
    ________,
    ________,
    ____X___,
    ____X___,
    ____X___,
    ____X___,
    ____X___,
    ____X___,
    ____X___,
    X___X___,
    X___X___,
    _XXX____,
    ________,
    ________,
    ________
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_004B[ 32] =   /* code 004B, LATIN CAPITAL LETTER K */
{
    ________,________,
    ________,________,
    ________,________,
    _X______,X_______,
    _X_____X,________,
    _X____X_,________,
    _X___X__,________,
    _X__X___,________,
    _X_XX___,________,
    _XX__X__,________,
    _X____X_,________,
    _X_____X,________,
    _X______,X_______,
    ________,________,
    ________,________,
    ________,________
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_004C[ 16] =   /* code 004C, LATIN CAPITAL LETTER L */
{
    ________,
    ________,
    ________,
    _X______,
    _X______,
    _X______,
    _X______,
    _X______,
    _X______,
    _X______,
    _X______,
    _X______,
    _XXXXXX_,
    ________,
    ________,
    ________
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_004D[ 32] =   /* code 004D, LATIN CAPITAL LETTER M */
{
    ________,________,
    ________,________,
    ________,________,
    _X______,_X______,
    _XX_____,XX______,
    _XX_____,XX______,
    _X_X___X,_X______,
    _X_X___X,_X______,
    _X__X_X_,_X______,
    _X__X_X_,_X______,
    _X__X_X_,_X______,
    _X___X__,_X______,
    _X___X__,_X______,
    ________,________,
    ________,________,
    ________,________
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_004E[ 32] =   /* code 004E, LATIN CAPITAL LETTER N */
{
    ________,________,
    ________,________,
    ________,________,
    _X_____X,________,
    _XX____X,________,
    _X_X___X,________,
    _X_X___X,________,
    _X__X__X,________,
    _X__X__X,________,
    _X___X_X,________,
    _X___X_X,________,
    _X____XX,________,
    _X_____X,________,
    ________,________,
    ________,________,
    ________,________
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_004F[ 32] =   /* code 004F, LATIN CAPITAL LETTER O */
{
    ________,________,
    ________,________,
    ________,________,
    ___XXXX_,________,
    __X____X,________,
    _X______,X_______,
    _X______,X_______,
    _X______,X_______,
    _X______,X_______,
    _X______,X_______,
    _X______,X_______,
    __X____X,________,
    ___XXXX_,________,
    ________,________,
    ________,________,
    ________,________
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_0050[ 32] =   /* code 0050, LATIN CAPITAL LETTER P */
{
    ________,________,
    ________,________,
    ________,________,
    _XXXXXX_,________,
    _X_____X,________,
    _X_____X,________,
    _X_____X,________,
    _X_____X,________,
    _XXXXXX_,________,
    _X______,________,
    _X______,________,
    _X______,________,
    _X______,________,
    ________,________,
    ________,________,
    ________,________
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_0051[ 32] =   /* code 0051, LATIN CAPITAL LETTER Q */
{
    ________,________,
    ________,________,
    ________,________,
    ___XXXX_,________,
    __X____X,________,
    _X______,X_______,
    _X______,X_______,
    _X______,X_______,
    _X______,X_______,
    _X______,X_______,
    _X___XX_,X_______,
    __X____X,________,
    ___XXXX_,X_______,
    ________,________,
    ________,________,
    ________,________
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_0052[ 32] =   /* code 0052, LATIN CAPITAL LETTER R */
{
    ________,________,
    ________,________,
    ________,________,
    _XXXXXX_,________,
    _X_____X,________,
    _X_____X,________,
    _X_____X,________,
    _X_____X,________,
    _XXXXXX_,________,
    _X___X__,________,
    _X____X_,________,
    _X____X_,________,
    _X_____X,________,
    ________,________,
    ________,________,
    ________,________
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_0053[ 32] =   /* code 0053, LATIN CAPITAL LETTER S */
{
    ________,________,
    ________,________,
    ________,________,
    __XXXXX_,________,
    _X_____X,________,
    _X_____X,________,
    _X______,________,
    __XXX___,________,
    _____XX_,________,
    _______X,________,
    _X_____X,________,
    _X_____X,________,
    __XXXXX_,________,
    ________,________,
    ________,________,
    ________,________
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_0054[ 16] =   /* code 0054, LATIN CAPITAL LETTER T */
{
    ________,
    ________,
    ________,
    XXXXXXX_,
    ___X____,
    ___X____,
    ___X____,
    ___X____,
    ___X____,
    ___X____,
    ___X____,
    ___X____,
    ___X____,
    ________,
    ________,
    ________
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_0055[ 32] =   /* code 0055, LATIN CAPITAL LETTER U */
{
    ________,________,
    ________,________,
    ________,________,
    _X_____X,________,
    _X_____X,________,
    _X_____X,________,
    _X_____X,________,
    _X_____X,________,
    _X_____X,________,
    _X_____X,________,
    _X_____X,________,
    __X___X_,________,
    ___XXX__,________,
    ________,________,
    ________,________,
    ________,________
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_0056[ 32] =   /* code 0056, LATIN CAPITAL LETTER V */
{
    ________,________,
    ________,________,
    ________,________,
    X_______,X_______,
    X_______,X_______,
    _X_____X,________,
    _X_____X,________,
    __X___X_,________,
    __X___X_,________,
    ___X_X__,________,
    ___X_X__,________,
    ____X___,________,
    ____X___,________,
    ________,________,
    ________,________,
    ________,________
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_0057[ 32] =   /* code 0057, LATIN CAPITAL LETTER W */
{
    ________,________,
    ________,________,
    ________,________,
    X_____X_,____X___,
    X____X_X,____X___,
    _X___X_X,___X____,
    _X___X_X,___X____,
    _X___X_X,___X____,
    __X_X___,X_X_____,
    __X_X___,X_X_____,
    __X_X___,X_X_____,
    ___X____,_X______,
    ___X____,_X______,
    ________,________,
    ________,________,
    ________,________
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_0058[ 16] =   /* code 0058, LATIN CAPITAL LETTER X */
{
    ________,
    ________,
    ________,
    X_____X_,
    _X___X__,
    _X___X__,
    __X_X___,
    ___X____,
    ___X____,
    __X_X___,
    _X___X__,
    _X___X__,
    X_____X_,
    ________,
    ________,
    ________
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_0059[ 32] =   /* code 0059, LATIN CAPITAL LETTER Y */
{
    ________,________,
    ________,________,
    ________,________,
    _X_____X,________,
    __X___X_,________,
    __X___X_,________,
    ___X_X__,________,
    ___X_X__,________,
    ____X___,________,
    ____X___,________,
    ____X___,________,
    ____X___,________,
    ____X___,________,
    ________,________,
    ________,________,
    ________,________
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_005A[ 16] =   /* code 005A, LATIN CAPITAL LETTER Z */
{
    ________,
    ________,
    ________,
    _XXXXXX_,
    _____X__,
    ____X___,
    ____X___,
    ___X____,
    ___X____,
    __X_____,
    __X_____,
    _X______,
    XXXXXXX_,
    ________,
    ________,
    ________
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_005B[ 16] =   /* code 005B, LEFT SQUARE BRACKET */
{
    ________,
    ________,
    ________,
    _XX_____,
    _X______,
    _X______,
    _X______,
    _X______,
    _X______,
    _X______,
    _X______,
    _X______,
    _X______,
    _X______,
    _X______,
    _XX_____
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_005C[ 16] =   /* code 005C, REVERSE SOLIDUS */
{
    ________,
    ________,
    ________,
    X_______,
    X_______,
    _X______,
    _X______,
    _X______,
    __X_____,
    __X_____,
    __X_____,
    ___X____,
    ___X____,
    ________,
    ________,
    ________
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_005D[ 16] =   /* code 005D, RIGHT SQUARE BRACKET */
{
    ________,
    ________,
    ________,
    _XX_____,
    __X_____,
    __X_____,
    __X_____,
    __X_____,
    __X_____,
    __X_____,
    __X_____,
    __X_____,
    __X_____,
    __X_____,
    __X_____,
    _XX_____
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_005E[ 16] =   /* code 005E, CIRCUMFLEX ACCENT */
{
    ________,
    ________,
    ________,
    ________,
    __X_____,
    _X_X____,
    _X_X____,
    _X_X____,
    X___X___,
    ________,
    ________,
    ________,
    ________,
    ________,
    ________,
    ________
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_005F[ 16] =   /* code 005F, LOW LINE */
{
    ________,
    ________,
    ________,
    ________,
    ________,
    ________,
    ________,
    ________,
    ________,
    ________,
    ________,
    ________,
    ________,
    ________,
    ________,
    XXXXXXX_
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_0060[ 16] =   /* code 0060, GRAVE ACCENT */
{
    ________,
    ________,
    ________,
    _X______,
    __X_____,
    ________,
    ________,
    ________,
    ________,
    ________,
    ________,
    ________,
    ________,
    ________,
    ________,
    ________
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_0061[ 16] =   /* code 0061, LATIN SMALL LETTER A */
{
    ________,
    ________,
    ________,
    ________,
    ________,
    ________,
    __XXX___,
    _X___X__,
    _____X__,
    __XXXX__,
    _X___X__,
    _X__XX__,
    __XX_X__,
    ________,
    ________,
    ________
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_0062[ 16] =   /* code 0062, LATIN SMALL LETTER B */
{
    ________,
    ________,
    ________,
    _X______,
    _X______,
    _X______,
    _X_XX___,
    _XX__X__,
    _X___X__,
    _X___X__,
    _X___X__,
    _X___X__,
    _XXXX___,
    ________,
    ________,
    ________
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_0063[ 16] =   /* code 0063, LATIN SMALL LETTER C */
{
    ________,
    ________,
    ________,
    ________,
    ________,
    ________,
    __XXX___,
    _X___X__,
    _X______,
    _X______,
    _X______,
    _X___X__,
    __XXX___,
    ________,
    ________,
    ________
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_0064[ 16] =   /* code 0064, LATIN SMALL LETTER D */
{
    ________,
    ________,
    ________,
    _____X__,
    _____X__,
    _____X__,
    __XX_X__,
    _X__XX__,
    _X___X__,
    _X___X__,
    _X___X__,
    _X___X__,
    __XXXX__,
    ________,
    ________,
    ________
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_0065[ 16] =   /* code 0065, LATIN SMALL LETTER E */
{
    ________,
    ________,
    ________,
    ________,
    ________,
    ________,
    __XXX___,
    _X___X__,
    _X___X__,
    _XXXXX__,
    _X______,
    _X___X__,
    __XXX___,
    ________,
    ________,
    ________
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_0066[ 16] =   /* code 0066, LATIN SMALL LETTER F */
{
    ________,
    ________,
    ________,
    __X_____,
    _X______,
    _X______,
    XXX_____,
    _X______,
    _X______,
    _X______,
    _X______,
    _X______,
    _X______,
    ________,
    ________,
    ________
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_0067[ 16] =   /* code 0067, LATIN SMALL LETTER G */
{
    ________,
    ________,
    ________,
    ________,
    ________,
    ________,
    __XX_X__,
    _X__XX__,
    _X___X__,
    _X___X__,
    _X___X__,
    _X__XX__,
    __XX_X__,
    _____X__,
    _X___X__,
    __XXX___
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_0068[ 16] =   /* code 0068, LATIN SMALL LETTER H */
{
    ________,
    ________,
    ________,
    _X______,
    _X______,
    _X______,
    _X_XX___,
    _XX__X__,
    _X___X__,
    _X___X__,
    _X___X__,
    _X___X__,
    _X___X__,
    ________,
    ________,
    ________
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_0069[ 16] =   /* code 0069, LATIN SMALL LETTER I */
{
    ________,
    ________,
    ________,
    _X______,
    ________,
    ________,
    _X______,
    _X______,
    _X______,
    _X______,
    _X______,
    _X______,
    _X______,
    ________,
    ________,
    ________
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_006A[ 16] =   /* code 006A, LATIN SMALL LETTER J */
{
    ________,
    ________,
    ________,
    _X______,
    ________,
    ________,
    _X______,
    _X______,
    _X______,
    _X______,
    _X______,
    _X______,
    _X______,
    _X______,
    _X______,
    X_______
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_006B[ 16] =   /* code 006B, LATIN SMALL LETTER K */
{
    ________,
    ________,
    ________,
    _X______,
    _X______,
    _X______,
    _X___X__,
    _X__X___,
    _X_X____,
    _XXX____,
    _X__X___,
    _X__X___,
    _X___X__,
    ________,
    ________,
    ________
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_006C[ 16] =   /* code 006C, LATIN SMALL LETTER L */
{
    ________,
    ________,
    ________,
    _X______,
    _X______,
    _X______,
    _X______,
    _X______,
    _X______,
    _X______,
    _X______,
    _X______,
    _X______,
    ________,
    ________,
    ________
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_006D[ 32] =   /* code 006D, LATIN SMALL LETTER M */
{
    ________,________,
    ________,________,
    ________,________,
    ________,________,
    ________,________,
    ________,________,
    _X_XX__X,X_______,
    _XX__XX_,_X______,
    _X___X__,_X______,
    _X___X__,_X______,
    _X___X__,_X______,
    _X___X__,_X______,
    _X___X__,_X______,
    ________,________,
    ________,________,
    ________,________
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_006E[ 16] =   /* code 006E, LATIN SMALL LETTER N */
{
    ________,
    ________,
    ________,
    ________,
    ________,
    ________,
    _X_XX___,
    _XX__X__,
    _X___X__,
    _X___X__,
    _X___X__,
    _X___X__,
    _X___X__,
    ________,
    ________,
    ________
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_006F[ 16] =   /* code 006F, LATIN SMALL LETTER O */
{
    ________,
    ________,
    ________,
    ________,
    ________,
    ________,
    __XXX___,
    _X___X__,
    _X___X__,
    _X___X__,
    _X___X__,
    _X___X__,
    __XXX___,
    ________,
    ________,
    ________
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_0070[ 16] =   /* code 0070, LATIN SMALL LETTER P */
{
    ________,
    ________,
    ________,
    ________,
    ________,
    ________,
    _X_XX___,
    _XX__X__,
    _X___X__,
    _X___X__,
    _X___X__,
    _XX__X__,
    _X_XX___,
    _X______,
    _X______,
    _X______
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_0071[ 16] =   /* code 0071, LATIN SMALL LETTER Q */
{
    ________,
    ________,
    ________,
    ________,
    ________,
    ________,
    __XX_X__,
    _X__XX__,
    _X___X__,
    _X___X__,
    _X___X__,
    _X__XX__,
    __XX_X__,
    _____X__,
    _____X__,
    _____X__
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_0072[ 16] =   /* code 0072, LATIN SMALL LETTER R */
{
    ________,
    ________,
    ________,
    ________,
    ________,
    ________,
    _X_X____,
    _XX_____,
    _X______,
    _X______,
    _X______,
    _X______,
    _X______,
    ________,
    ________,
    ________
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_0073[ 16] =   /* code 0073, LATIN SMALL LETTER S */
{
    ________,
    ________,
    ________,
    ________,
    ________,
    ________,
    __XXX___,
    _X___X__,
    _X______,
    __XXX___,
    _____X__,
    _X___X__,
    __XXX___,
    ________,
    ________,
    ________
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_0074[ 16] =   /* code 0074, LATIN SMALL LETTER T */
{
    ________,
    ________,
    ________,
    ________,
    _X______,
    _X______,
    XXX_____,
    _X______,
    _X______,
    _X______,
    _X______,
    _X______,
    _XX_____,
    ________,
    ________,
    ________
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_0075[ 16] =   /* code 0075, LATIN SMALL LETTER U */
{
    ________,
    ________,
    ________,
    ________,
    ________,
    ________,
    _X___X__,
    _X___X__,
    _X___X__,
    _X___X__,
    _X___X__,
    _X___X__,
    __XXXX__,
    ________,
    ________,
    ________
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_0076[ 16] =   /* code 0076, LATIN SMALL LETTER V */
{
    ________,
    ________,
    ________,
    ________,
    ________,
    ________,
    X___X___,
    X___X___,
    _X_X____,
    _X_X____,
    _X_X____,
    __X_____,
    __X_____,
    ________,
    ________,
    ________
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_0077[ 32] =   /* code 0077, LATIN SMALL LETTER W */
{
    ________,________,
    ________,________,
    ________,________,
    ________,________,
    ________,________,
    ________,________,
    X___X___,X_______,
    X___X___,X_______,
    _X_X_X_X,________,
    _X_X_X_X,________,
    _X_X_X_X,________,
    __X___X_,________,
    __X___X_,________,
    ________,________,
    ________,________,
    ________,________
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_0078[ 16] =   /* code 0078, LATIN SMALL LETTER X */
{
    ________,
    ________,
    ________,
    ________,
    ________,
    ________,
    _X___X__,
    __X_X___,
    __X_X___,
    ___X____,
    __X_X___,
    __X_X___,
    _X___X__,
    ________,
    ________,
    ________
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_0079[ 16] =   /* code 0079, LATIN SMALL LETTER Y */
{
    ________,
    ________,
    ________,
    ________,
    ________,
    ________,
    _X___X__,
    _X___X__,
    __X_X___,
    __X_X___,
    __X_X___,
    ___X____,
    ___X____,
    ___X____,
    ___X____,
    _XX_____
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_007A[ 16] =   /* code 007A, LATIN SMALL LETTER Z */
{
    ________,
    ________,
    ________,
    ________,
    ________,
    ________,
    _XXXXX__,
    ____X___,
    ____X___,
    ___X____,
    __X_____,
    __X_____,
    _XXXXX__,
    ________,
    ________,
    ________
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_007B[ 16] =   /* code 007B, LEFT CURLY BRACKET */
{
    ________,
    ________,
    ________,
    __X_____,
    _X______,
    _X______,
    _X______,
    _X______,
    _X______,
    X_______,
    _X______,
    _X______,
    _X______,
    _X______,
    _X______,
    __X_____
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_007C[ 16] =   /* code 007C, VERTICAL LINE */
{
    ________,
    ________,
    ________,
    _X______,
    _X______,
    _X______,
    _X______,
    _X______,
    _X______,
    _X______,
    _X______,
    _X______,
    _X______,
    _X______,
    _X______,
    ________
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_007D[ 16] =   /* code 007D, RIGHT CURLY BRACKET */
{
    ________,
    ________,
    ________,
    _X______,
    __X_____,
    __X_____,
    __X_____,
    __X_____,
    __X_____,
    ___X____,
    __X_____,
    __X_____,
    __X_____,
    __X_____,
    __X_____,
    _X______
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_007E[ 16] =   /* code 007E, TILDE */
{
    ________,
    ________,
    ________,
    ________,
    ________,
    ________,
    ________,
    _XXX__X_,
    X__XXXX_,
    ________,
    ________,
    ________,
    ________,
    ________,
    ________,
    ________
};

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_679C[ 48] =   /* code 679C */
{
    ________,________,________,
    ________,________,________,
    ________,________,________,
    _____XXX,XXXXXX__,________,
    _____X__,_X___X__,________,
    _____XXX,XXXXXX__,________,
    _____X__,_X___X__,________,
    _____XXX,XXXXXX__,________,
    ________,_X______,________,
    ___XXXXX,XXXXXXXX,________,
    ________,XXX_____,________,
    _______X,_X_X____,________,
    ______X_,_X__X___,________,
    _____X__,_X___X__,________,
    ____X___,_X____X_,________,
    ________,________,________
};

GUI_CONST_STORAGE unsigned char acGUI_FontNVTFont16_7D50[ 48] =   /* code 7D50 */
{
    ________,________,________,
    ________,________,________,
    ________,________,________,
    ________,________,________,
    ____XX__,_____X__,________,
    ___XX___,__XXXXXX,X_______,
    __XX__XX,_____X__,________,
    _XX__XX_,__XXXXXX,X_______,
    __XXXX__,________,________,
    ____X__X,___XXXXX,X_______,
    ___X__XX,X__X____,X_______,
    __XXXXX_,XX_X____,X_______,
    ________,___XXXXX,X_______,
    __X_X_X_,________,________,
    ________,________,________,
    ________,________,________
};

GUI_CONST_STORAGE GUI_CHARINFO GUI_FontNVTFont16_CharInfo[97] =
{
    {   4,   4,  1, acGUI_FontNVTFont16_0020 } /* code 0020 */
    ,{   3,   3,  1, acGUI_FontNVTFont16_0021 } /* code 0021 */
    ,{   5,   5,  1, acGUI_FontNVTFont16_0022 } /* code 0022 */
    ,{   7,   7,  1, acGUI_FontNVTFont16_0023 } /* code 0023 */
    ,{   7,   7,  1, acGUI_FontNVTFont16_0024 } /* code 0024 */
    ,{  12,  12,  2, acGUI_FontNVTFont16_0025 } /* code 0025 */
    ,{   9,   9,  2, acGUI_FontNVTFont16_0026 } /* code 0026 */
    ,{   2,   2,  1, acGUI_FontNVTFont16_0027 } /* code 0027 */
    ,{   4,   4,  1, acGUI_FontNVTFont16_0028 } /* code 0028 */
    ,{   4,   4,  1, acGUI_FontNVTFont16_0029 } /* code 0029 */
    ,{   5,   5,  1, acGUI_FontNVTFont16_002A } /* code 002A */
    ,{   8,   8,  1, acGUI_FontNVTFont16_002B } /* code 002B */
    ,{   4,   4,  1, acGUI_FontNVTFont16_002C } /* code 002C */
    ,{   4,   4,  1, acGUI_FontNVTFont16_002D } /* code 002D */
    ,{   4,   4,  1, acGUI_FontNVTFont16_002E } /* code 002E */
    ,{   4,   4,  1, acGUI_FontNVTFont16_002F } /* code 002F */
    ,{   7,   7,  1, acGUI_FontNVTFont16_0030 } /* code 0030 */
    ,{   7,   7,  1, acGUI_FontNVTFont16_0031 } /* code 0031 */
    ,{   7,   7,  1, acGUI_FontNVTFont16_0032 } /* code 0032 */
    ,{   7,   7,  1, acGUI_FontNVTFont16_0033 } /* code 0033 */
    ,{   7,   7,  1, acGUI_FontNVTFont16_0034 } /* code 0034 */
    ,{   7,   7,  1, acGUI_FontNVTFont16_0035 } /* code 0035 */
    ,{   7,   7,  1, acGUI_FontNVTFont16_0036 } /* code 0036 */
    ,{   7,   7,  1, acGUI_FontNVTFont16_0037 } /* code 0037 */
    ,{   7,   7,  1, acGUI_FontNVTFont16_0038 } /* code 0038 */
    ,{   7,   7,  1, acGUI_FontNVTFont16_0039 } /* code 0039 */
    ,{   4,   4,  1, acGUI_FontNVTFont16_003A } /* code 003A */
    ,{   4,   4,  1, acGUI_FontNVTFont16_003B } /* code 003B */
    ,{   8,   8,  1, acGUI_FontNVTFont16_003C } /* code 003C */
    ,{   8,   8,  1, acGUI_FontNVTFont16_003D } /* code 003D */
    ,{   8,   8,  1, acGUI_FontNVTFont16_003E } /* code 003E */
    ,{   7,   7,  1, acGUI_FontNVTFont16_003F } /* code 003F */
    ,{  13,  13,  2, acGUI_FontNVTFont16_0040 } /* code 0040 */
    ,{   9,   9,  2, acGUI_FontNVTFont16_0041 } /* code 0041 */
    ,{   9,   9,  2, acGUI_FontNVTFont16_0042 } /* code 0042 */
    ,{   9,   9,  2, acGUI_FontNVTFont16_0043 } /* code 0043 */
    ,{   9,   9,  2, acGUI_FontNVTFont16_0044 } /* code 0044 */
    ,{   9,   9,  2, acGUI_FontNVTFont16_0045 } /* code 0045 */
    ,{   8,   8,  1, acGUI_FontNVTFont16_0046 } /* code 0046 */
    ,{  10,  10,  2, acGUI_FontNVTFont16_0047 } /* code 0047 */
    ,{   9,   9,  2, acGUI_FontNVTFont16_0048 } /* code 0048 */
    ,{   3,   3,  1, acGUI_FontNVTFont16_0049 } /* code 0049 */
    ,{   6,   6,  1, acGUI_FontNVTFont16_004A } /* code 004A */
    ,{   9,   9,  2, acGUI_FontNVTFont16_004B } /* code 004B */
    ,{   7,   7,  1, acGUI_FontNVTFont16_004C } /* code 004C */
    ,{  11,  11,  2, acGUI_FontNVTFont16_004D } /* code 004D */
    ,{   9,   9,  2, acGUI_FontNVTFont16_004E } /* code 004E */
    ,{  10,  10,  2, acGUI_FontNVTFont16_004F } /* code 004F */
    ,{   9,   9,  2, acGUI_FontNVTFont16_0050 } /* code 0050 */
    ,{  10,  10,  2, acGUI_FontNVTFont16_0051 } /* code 0051 */
    ,{   9,   9,  2, acGUI_FontNVTFont16_0052 } /* code 0052 */
    ,{   9,   9,  2, acGUI_FontNVTFont16_0053 } /* code 0053 */
    ,{   7,   7,  1, acGUI_FontNVTFont16_0054 } /* code 0054 */
    ,{   9,   9,  2, acGUI_FontNVTFont16_0055 } /* code 0055 */
    ,{   9,   9,  2, acGUI_FontNVTFont16_0056 } /* code 0056 */
    ,{  13,  13,  2, acGUI_FontNVTFont16_0057 } /* code 0057 */
    ,{   7,   7,  1, acGUI_FontNVTFont16_0058 } /* code 0058 */
    ,{   9,   9,  2, acGUI_FontNVTFont16_0059 } /* code 0059 */
    ,{   7,   7,  1, acGUI_FontNVTFont16_005A } /* code 005A */
    ,{   4,   4,  1, acGUI_FontNVTFont16_005B } /* code 005B */
    ,{   4,   4,  1, acGUI_FontNVTFont16_005C } /* code 005C */
    ,{   4,   4,  1, acGUI_FontNVTFont16_005D } /* code 005D */
    ,{   5,   5,  1, acGUI_FontNVTFont16_005E } /* code 005E */
    ,{   7,   7,  1, acGUI_FontNVTFont16_005F } /* code 005F */
    ,{   4,   4,  1, acGUI_FontNVTFont16_0060 } /* code 0060 */
    ,{   7,   7,  1, acGUI_FontNVTFont16_0061 } /* code 0061 */
    ,{   7,   7,  1, acGUI_FontNVTFont16_0062 } /* code 0062 */
    ,{   7,   7,  1, acGUI_FontNVTFont16_0063 } /* code 0063 */
    ,{   7,   7,  1, acGUI_FontNVTFont16_0064 } /* code 0064 */
    ,{   7,   7,  1, acGUI_FontNVTFont16_0065 } /* code 0065 */
    ,{   3,   3,  1, acGUI_FontNVTFont16_0066 } /* code 0066 */
    ,{   7,   7,  1, acGUI_FontNVTFont16_0067 } /* code 0067 */
    ,{   7,   7,  1, acGUI_FontNVTFont16_0068 } /* code 0068 */
    ,{   3,   3,  1, acGUI_FontNVTFont16_0069 } /* code 0069 */
    ,{   3,   3,  1, acGUI_FontNVTFont16_006A } /* code 006A */
    ,{   7,   7,  1, acGUI_FontNVTFont16_006B } /* code 006B */
    ,{   3,   3,  1, acGUI_FontNVTFont16_006C } /* code 006C */
    ,{  11,  11,  2, acGUI_FontNVTFont16_006D } /* code 006D */
    ,{   7,   7,  1, acGUI_FontNVTFont16_006E } /* code 006E */
    ,{   7,   7,  1, acGUI_FontNVTFont16_006F } /* code 006F */
    ,{   7,   7,  1, acGUI_FontNVTFont16_0070 } /* code 0070 */
    ,{   7,   7,  1, acGUI_FontNVTFont16_0071 } /* code 0071 */
    ,{   4,   4,  1, acGUI_FontNVTFont16_0072 } /* code 0072 */
    ,{   7,   7,  1, acGUI_FontNVTFont16_0073 } /* code 0073 */
    ,{   4,   4,  1, acGUI_FontNVTFont16_0074 } /* code 0074 */
    ,{   7,   7,  1, acGUI_FontNVTFont16_0075 } /* code 0075 */
    ,{   5,   5,  1, acGUI_FontNVTFont16_0076 } /* code 0076 */
    ,{   9,   9,  2, acGUI_FontNVTFont16_0077 } /* code 0077 */
    ,{   7,   7,  1, acGUI_FontNVTFont16_0078 } /* code 0078 */
    ,{   7,   7,  1, acGUI_FontNVTFont16_0079 } /* code 0079 */
    ,{   7,   7,  1, acGUI_FontNVTFont16_007A } /* code 007A */
    ,{   4,   4,  1, acGUI_FontNVTFont16_007B } /* code 007B */
    ,{   3,   3,  1, acGUI_FontNVTFont16_007C } /* code 007C */
    ,{   4,   4,  1, acGUI_FontNVTFont16_007D } /* code 007D */
    ,{   8,   8,  1, acGUI_FontNVTFont16_007E } /* code 007E */
    ,{  21,  21,  3, acGUI_FontNVTFont16_679C } /* code 679C */
    ,{  21,  21,  3, acGUI_FontNVTFont16_7D50 } /* code 7D50 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontNVTFont16_Prop3 =
{
    0x7D50 /* first character */
    ,0x7D50 /* last character  */
    ,&GUI_FontNVTFont16_CharInfo[ 96] /* address of first character */
    ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontNVTFont16_Prop2 =
{
    0x679C /* first character */
    ,0x679C /* last character  */
    ,&GUI_FontNVTFont16_CharInfo[ 95] /* address of first character */
    ,&GUI_FontNVTFont16_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontNVTFont16_Prop1 =
{
    0x0020 /* first character */
    ,0x007E /* last character  */
    ,&GUI_FontNVTFont16_CharInfo[  0] /* address of first character */
    ,&GUI_FontNVTFont16_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontNVTFont16 =
{
    GUI_FONTTYPE_PROP /* type of font    */
    ,16 /* height of font  */
    ,16 /* space of font y */
    ,1 /* magnification x */
    ,1 /* magnification y */
    ,{&GUI_FontNVTFont16_Prop1}
    ,13 /* Baseline */
    ,7 /* Height of lowercase characters */
    ,10 /* Height of capital characters */
};

